### PR TITLE
Create a NuGet.Config file as part of solution

### LINKED ISSUE #512: Cannot create Roslyn SDK Sample
There are a few problems:

1) The SDK Templates all say they're .NET Standard. However, the framework selector only shows .NET Framework Versions:
image

2) Clicking create returns a sequence contains no elements exception. Stack:
```
 	System.Core.dll!System.Linq.Enumerable.Last<System.Xml.Linq.XElement>(System.Collections.Generic.IEnumerable<System.Xml.Linq.XElement> source)	Unknown
>	Roslyn.SDK.Template.Wizard.dll!RoslynSDKRootTemplateWizard.WriteOutBetaNugetSource(string key, string value) Line 36	C#
 	Roslyn.SDK.Template.Wizard.dll!RoslynSDKRootTemplateWizard.RunStarted(object automationObject, System.Collections.Generic.Dictionary<string, string> replacementsDictionary, Microsoft.VisualStudio.TemplateWizard.WizardRunKind runKind, object[] customParams) Line 21	C#
 	Microsoft.VisualStudio.TemplateWizard.dll!Microsoft.VisualStudio.TemplateWizard.Wizard.Execute(object application, int hwndOwner, ref object[] ContextParams, ref object[] CustomParams, ref EnvDTE.wizardResult retval)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	Microsoft.VisualStudio.Dialogs.dll!Microsoft.VisualStudio.Dialogs.ServiceHelper.AddProjectFromSelectedTemplate(Microsoft.VisualStudio.Dialogs.INewProjectDialogData dialog)	Unknown
 	Microsoft.VisualStudio.Dialogs.dll!Microsoft.VisualStudio.NewProjectDialog.NewProjectDialogServices.CreateProject(Microsoft.VisualStudio.Dialogs.INewProjectDialogData npdd)	Unknown
 	Microsoft.VisualStudio.Dialogs.dll!Microsoft.VisualStudio.NewProjectDialog.ProjectConfigurationViewModel.CreateProject()	Unknown
 	Microsoft.VisualStudio.Dialogs.dll!Microsoft.VisualStudio.NewProjectDialog.NpdStateMachine.End()	Unknown
 	Microsoft.VisualStudio.Dialogs.dll!Microsoft.VisualStudio.NewProjectDialog.NewProjectDialogViewModel.OnGoNext(object parameter)	Unknown
 	Microsoft.VisualStudio.Utilities.dll!Microsoft.VisualStudio.PlatformUI.DelegateCommand<object>.Execute(object parameter)	Unknown
 	Microsoft.VisualStudio.Utilities.dll!Microsoft.VisualStudio.PlatformUI.DispatchedDelegateCommand<object>.Execute.AnonymousMethod__0()	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs)	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, System.Delegate callback, object args, int numArgs, System.Delegate catchHandler)	Unknown
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.InvokeImpl()	Unknown
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(object state)	Unknown
 	WindowsBase.dll!MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(object obj)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 980	C#
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 928	C#
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state) Line 917	C#
 	WindowsBase.dll!MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.Invoke()	Unknown
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.ProcessQueue()	Unknown
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.WndProcHook(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled)	Unknown
 	WindowsBase.dll!MS.Win32.HwndWrapper.WndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled)	Unknown
 	WindowsBase.dll!MS.Win32.HwndSubclass.DispatcherCallbackOperation(object o)	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs)	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, System.Delegate callback, object args, int numArgs, System.Delegate catchHandler)	Unknown
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority priority, System.TimeSpan timeout, System.Delegate method, object args, int numArgs)	Unknown
 	WindowsBase.dll!MS.Win32.HwndSubclass.SubclassWndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam)	Unknown
```
Dump: https://1drv.ms/u/s!AkgwhGshn8Uyz4JaJM6legLb8MtZbg?e=igd1GM

### PR DESCRIPTION
**Pull request by sharwell**
Closes #512

### CODE REVIEW

**Comment by jmarolf** [comment]
maybe we just publish this package to nuget?

**Comment by sharwell** [comment]
Even if we publish the package to NuGet, we'll want to have this configuration in place for people who want to update more frequently (as best I can tell, it would apply to everyone working on analyzers).

**Comment by jmarolf** [comment]
> who want to update more frequently

We could just tell folks how to add a myget source. considering this is a very difficult area to test and has broken I am worried about taking this approach instead of just using nuget.org

**Comment by sharwell** [comment]
For now, merging this as an incremental improvement (NuGet.Config with the solution is better than manipulating a machine configuration file). We may move this to nuget.org in the future and eliminate the need for this, but we still want the templates to work well for people prior to finalizing that work.

**Pull request merged**
