### PR TITLE
Fix namespaces of VB test types

### PR DESCRIPTION
**Pull request by sharwell**

### CODE REVIEW

**Comment by jmarolf** [comment]
Visual Basic places classes automatically within the default namespace specified in the project file.  The other changes that move classes to separate files seem fine though.

**Comment by sharwell** [comment]
> Visual Basic places classes automatically within the default namespace specified in the project file.

This was not the case when I used the output assemblies in other projects.

**Comment by jmarolf** [comment]
> This was not the case when I used the output assemblies in other projects.

yep, I just confirmed you are correct

**Comment by sharwell** [comment]
I'm happy to revert this if we find out in the future it was a configuration mistake or there is some better way to do the same thing. :+1:

**Pull request merged**
