### PR TITLE
Rename AnalysisExclusions to TestBehaviors

### PR DESCRIPTION
**Pull request by sharwell**
Inverting the flags allows future additions to this enumeration without invalidating code that sets the property using the object initializer syntax in tests.

### CODE REVIEW

**Comment by jmarolf** [comment]
Could we call these `AnalysisOptions` instead of `Quirks`?

**Comment by sharwell** [comment]
@jmarolf We could. The reason I somewhat like 'quirks' is these typically represent deviations from the most common (and expected) analyzer patterns.

**Comment by jmarolf** [comment]
I guess I feel quirks is a little presumptive.  Yes this is a much more advanced option but for someone that needs to verify this sort of thing this is not a quirk. As you say `AnalysisOptions` is probably not good enough. Perhaps just `AdditionalOptions`?

**Comment by sharwell** [comment]
After some brainstorming we settled on `TestBehaviors`

**Pull request merged**
