### PR TITLE
Fix Symbol View In SyntaxTreeVizualizer

### PR DESCRIPTION
**Pull request by bernd5**
See:
- https://github.com/dotnet/roslyn-sdk/pull/554
- https://github.com/dotnet/roslyn-sdk/issues/504

=> Use custom TypeDescriptor to display Symbol-Data

### CODE REVIEW

**Comment by sharwell** [comment]
Do you know why a custom TypeDescriptor is needed for displaying `ISymbol`, but is not needed for displaying `IOperation`?

**Comment by bernd5** [comment]
What happens inside of the property grid is a call like this:

````
var props = TypeDescriptor.GetProperties(node, new Attribute[] { BrowsableAttribute.Yes });
```
which calls then (more or less):
```
new ReflectTypeDescriptionProvider().GetProperties(node.GetType())
```

For SyntaxNodes it returns some properties (perhaps because of some attributes). But for symbols it returns nothing.

**Comment by bernd5** [comment]
That makes sense, we have the type of the Symbol implementation not the Symbol itself.

**Comment by bernd5** [comment]
We could use the adapter for all kinds of selected objects, it allow a better control...
For example we can print now "None" instead of an empty string.

**Comment by bernd5** [comment]
do you want to merge it or should I change something?

**Review by jmarolf — APPROVED** [review]
:shipit:

**Comment by jmarolf** [comment]
Thanks @bernd5! I'll go ahead and merge this in

**Pull request merged**
