### PR TITLE
Update DiffPlex to consider whitespace as differences

### PR DESCRIPTION
**Pull request by sharwell**

### CODE REVIEW

**Comment by jmarolf** [comment]
@sharwell 	can you give an example of why this change is needed?

**Comment by sharwell** [comment]
@jmarolf If a code fix makes a change and the indentation is wrong, the test will fail but the diff output will not show which lines resulted in the failure.

**Comment by sharwell** [comment]
I'll try to get a test added that shows this.

**Comment by sharwell** [comment]
@jmarolf I rebased this to add a test showing the behavior before this change, and then applied the change and updated the test to show the new expected results.

**Pull request merged**
