### PR TITLE
Don't run tests during official build

### PR DESCRIPTION
**Pull request by JoeRobich**
Test build: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6657192&view=results (microsoft)

### CODE REVIEW

**Comment by JoeRobich** [comment]
@jmarolf Switching to the powershell tasks fixed the signed build. This PR should be good to merge once reviewed.

**Comment by sharwell** [comment]
@JoeRobich The internal build still seems to be red. Not sure I'm looking at the correct link though.

**Comment by JoeRobich** [comment]
@sharwell Yeah, apparently when you don't run tests you don't need to publish test artifacts. whoops

**Review by dibarbet — APPROVED** [review]

**Pull request merged**
