### PR TITLE
Use ProjectReference magic from Rainer

### PR DESCRIPTION
**Pull request by cartermp**
From @rainersigwald here: https://twitter.com/Tashkant/status/1256749223850266624

### CODE REVIEW

**Comment by cartermp** [comment]
verified locally on my mac, I suppose I should also make sure this doesn't make VS go wonky

**Comment by cartermp** [comment]
Luckily, source generators are only supported as netstandard2.0 components!

**Comment by loic-sharma** [comment]
@cartermp should we also update the [`srcgen4.csproj` snippet](https://gist.github.com/cartermp/5304f2a2bca26099ad249c6d7a6f8e90#file-srcgen4-csproj) in the [blog post](https://devblogs.microsoft.com/dotnet/introducing-c-source-generators/)? I personally started my project by following the blog post :)

**Comment by cartermp** [comment]
@loic-sharma done!

**Comment by cartermp** [comment]
@sharwell FYI I don't have merge rights here. Could you merge it?

**Pull request merged**
